### ISSUE TITLE
Требования к полям атомов

### ISSUE THREAD

**Issue by pelageech** [Gopher-Co/td-game#2]
Необходимо явно прописать поля, которые можно будет редактировать и, после редактирования, маршаллить (отдельное задание в трекере).

Для каждого из модулей в редакторе написать такие поля:

- Карты
- Враги @peyuaa 
- Режимы игры (включает в себя врагов)
- Башни @peyuaa 
- UI @MIZINCHIK

**Comment by peyuaa** [comment]
В Miro все это указываем?

**Comment by pelageech** [comment]
Да, сначала в основной док в телеге (ссылку желательно в миро прикрепить), а потом в миро переписать

**Comment by pelageech** [comment]
> В Miro все это указываем?

Да, сначала в основной док в телеге (ссылку желательно в миро прикрепить), а потом в миро переписать
