### ISSUE TITLE
Use-Cases

### ISSUE THREAD

**Issue by pelageech** [Gopher-Co/td-game#5]
- [x] Выделить основных акторов
- [ ] Для каждого актора выделить юз-кейсы
- [ ] Описать эти юз кейсы

**Comment by pelageech** [comment]
Акторы: Player и Editor

**Comment by pelageech** [comment]
@peyuaa @MIZINCHIK юз-кейсы для Игрока

**Comment by peyuaa** [comment]
Actor: Player

Scenario:

- Initiating the Game
The player launches the Tower Defense game on their computer.
The game's main menu appears, offering options to start a new game, continue a previous one, or access settings and other features.

- Starting a New Game
The player selects "New Game" to begin a new Tower Defense challenge.
They may be prompted to choose a difficulty level or map, depending on the game's options.

- Choosing Towers
The player is presented with an empty game map or grid where enemies will travel along predetermined paths.
They have access to a limited amount of in-game currency, which they can use to purchase and place different types of towers on the map.
The player carefully selects and places their initial towers in strategic locations along the enemy's path, taking into account factors like the range, damage, and firing rate of each tower.

- Waves of Enemies
The game begins, and waves of enemy units start moving along the paths toward the player's base or goal.
The player observes the enemies and monitors their tower placements, making decisions to upgrade existing towers, sell inefficient ones, or purchase new ones based on the evolving threat.

- Earning Currency
As the player successfully defeats waves of enemies, they earn additional in-game currency.
This currency can be used to further enhance existing towers, unlock new tower types, or expand their defenses by placing more towers on the map.

- Strategic Decision-Making
The player must continuously make strategic decisions throughout the game, such as which towers to upgrade, where to place new towers, and when to use special abilities or power-ups.
Adaptation to different enemy types and their strengths and weaknesses is crucial to maintaining a strong defence.

- Progression and Challenges
The game progresses through multiple waves, with each wave typically becoming more challenging, introducing new enemy types, and increasing the difficulty.
The player must strategize and adapt to these changes, sometimes requiring quick thinking and resource management.

- Winning or Losing
The player's primary goal is to prevent the enemies from reaching their base or goal. If they successfully defend against all waves, they win the level and may advance to the next one.
If the enemies breach the defenses and reach their goal, the player loses the level, and they may have the option to retry or adjust their strategy.

- Achievements and Rewards
Depending on their performance in the game, the player may earn achievements, in-game rewards, or unlock new maps or challenges, providing an incentive to replay and improve their strategies.

- Exiting or Continuing
After completing a level or deciding to stop playing, the player can save their progress and return to the main menu or choose to continue the game from where they left off.

- Saving Progress
The player's progress is automatically saved or can be manually saved within the game, allowing them to pick up where they left off during their next gaming session.

**Comment by peyuaa** [comment]
Добавил в google docs, чекните что не нравится, можете отредачить
